name: matrix
on: [push, pull_request]


jobs:
build:
  strategy:
  matrix:
    java: [graalvm@, openjdk@1.8, openjdk@1.11, openjdk@1.13, openjdk@1.14, zulu@1.11]
  runs-on: ubuntu-latest
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v5
    - name: Compile
      run: sbt packageAll
